.circleci/config.yml
I accidentally removed a required parameter from the
persist_to_workspace action.
=> chore: fix the CircleCI config

.eslintrc.json, docs/contributing.md, jest.config.json, package-lock.json, package.json, packages/example/test/index.spec.js
This adds Jest as a unit test runner. We have it configured to run any
test files within the packages, which it will do in parallel. This means
our tests should remain nice and fast regardless of how many packages we
add to the repo.
I added an example test just to illustrate where they'll be written.
The tests should also automatically run in this PR.
=> chore: add unit test runner

docs/contributing.md, jsconfig.json, package-lock.json, package.json
We now explicitly check types with TypeScript, so that if we provide
valid JSDoc comments for our code we can be sure that everything is
type-safe. This will hopefully result in fewer unexpected bugs and
increase confidence in our tooling!
This also gives us useful hinting in VS Code, so hopefully writing the
code will be easier for us as well.
=> chore: add automated type checking

.eslintrc.json, jsconfig.json, package-lock.json, package.json
ESLint does not support many ES2020 features, e.g. class public and
private fields. It'd be nice to be able to use these considering that
we're only targeting environments where they're available.
This addresses the issue and makes sure that both ESLint and TypeScript
do not complain when we use modern features.
=> chore: use Babel with ESLint

packages/errors/README.md
@rowanmanning linked to this in #ft-next-dev. It's a good intro for people who are starting to think more seriously about error handling (as we are).
I don't think this will conflict with #14 but if it will we can merge it afterwards.
=> docs: link to Joyent's Error Handling documentation

package-lock.json
Not exactly sure what's going on here.
---
This is the result of running npm install on main. For some reason the version bump commit doesn't bump this part of package-lock.json
=> chore: bump errors package in root package-lock.json

.eslintrc.json
This ensures that we can use things like type unions in our code.
See https://github.com/gajus/eslint-plugin-jsdoc#mode for documentation.
=> chore: set the ESLint JSDoc mode to TypeScript

jsconfig.json
I found that I was really fighting TypeScript in the tests, because it's
often useful to mock with dummy data rather than fully mocking the
expected return values of methods.
This stops us from having to litter our tests with ts-ignore comments.
=> chore: don't check types in test files

packages/errors/README.md, packages/errors/lib/http-error.js, packages/errors/lib/index.js, packages/errors/lib/operational-error.js, packages/errors/test/lib/http-error.spec.js, packages/errors/test/lib/index.spec.js, packages/errors/test/lib/operational-error.spec.js
This PR is a little large, but I found it difficult to split across multiple PRs because everything is very tightly interlinked. What I have done is written it as [separate smaller commits](https://github.com/Financial-Times/dotcom-reliability-kit/pull/14/commits) which it's possible to review individually. A _lot_ of the added code is in the tests, which maybe don't need to be reviewed quite as thoroughly – I've managed to keep 100% coverage.
* I've finished writing the basics for an `OperationalError` class, which allows us to identify when an error is expected vs unexpected. Operational errors also _always_ have an error code so that we can reliably identify the errors when they're logged.
* I've added an `HttpError` class, which represents a 400–599 response. This is because …
=> Build errors package

docs/contributing.md, jsconfig.json, package.json, scripts/create-package.js
When I was setting up `packages/errors`, I missed a lot of things that
were required to get the package to be released with Release Please. I
also think it'll be easy to see some inconsistency in the way packages
are built the more we add them.
This PR adds a new script which automatically creates the boilerplate
for a new Reliability Kit package, taking a lot of inspiration from the
[equivalent script in Tool Kit](https://github.com/Financial-Times/dotcom-tool-kit/blob/main/scripts/create-plugin.js).
There's documentation on how the script is run in the contributing
guide, as I think that's where people would most likely look.
=> chore: write a script to create new packages

.release-please-manifest.json, README.md, package-lock.json, packages/serialize-error/.npmignore, packages/serialize-error/README.md, packages/serialize-error/lib/index.js, packages/serialize-error/package.json, packages/serialize-error/test/lib/index.spec.js, release-please-config.json
This adds a serialize-error utility package. This new package exports
a utility function to serialize an error object in a way that's friendly
to loggers, view engines, and converting to JSON.
I'm writing this because we need a reliable way to serialize error data
if we tackle any of the following:
* An error logging middleware so that thrown errors are logged
consistently to Splunk (planned)
* Modifications to `n-logger` to enforce more consistent logging of
errors (not planned but likely we will need it)
* A debugging page middleware which renders an HTML error page to help
engineers debug while working locally (planned)
I think it makes sense to publish this as a separate package which is a
dependency of these others.
See the README in this PR for usage documentation.
=> Build serialize-error package

.release-please-manifest.json, README.md, package-lock.json, packages/serialize-request/.npmignore, packages/serialize-request/README.md, packages/serialize-request/lib/index.js, packages/serialize-request/package.json, packages/serialize-request/test/lib/index.spec.js, release-please-config.json
This is the equivalent of the `serializeError` function but built to handle `Request` objects (either Express or plain Node.js `IncomingMessage`).
Most of the information needed to review this should be in the README (part of this PR). I'm matching our serialized request object to the current format outlined in [this discussion](https://github.com/Financial-Times/dotcom-reliability-kit/discussions/26) so it looks like this:
```js
{
id: 'request137',
method: 'GET',
url: '/fruit/feijoa',
headers: {
accept: '*/*'
},
route: {
path: '/fruit/:fruitId',
params: { fruitId: 'feijoa' }
}
}
```
I decided against trying to tackle an [API Gateway request](https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html#apigateway-example-event) for now. I think it should be possible to add …
=> Add a serialize-request package

.release-please-manifest.json, README.md, jsconfig.json, package-lock.json, packages/middleware-log-errors/.npmignore, packages/middleware-log-errors/README.md, packages/middleware-log-errors/lib/index.js, packages/middleware-log-errors/package.json, packages/middleware-log-errors/test/lib/index.spec.js, release-please-config.json
This adds error logging middleware based on the discussion in the repo
here: https://github.com/Financial-Times/dotcom-reliability-kit/discussions/26. It's relatively small because it leans on the [serialize-error](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/serialize-error#readme) and
[serialize-request](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/serialize-request#readme) packages.
You use it like this:
```js
import createErrorLogger from '@dotcom-reliability-kit/middleware-log-errors';
import express from '@financial-times/n-express';
// All your app setup and routes
app.use(createErrorLogger());
```
And all errors which get thrown in routes or passed onto Express
will end up logging all this information:
```js
{
event: …
```
=> feat: add error logging middleware

.github/settings.yml
This will ensure that the history as it's understood by Release Please
will be in the order that code was merged into `main` rather than the
order it was committed.
=> chore: only allow rebase merges

packages/middleware-log-errors/README.md
This is a copy/paste error that I somehow didn't spot. It's now
documented correctly.
=> docs: fix a copy/paste error in the README

docs/getting-started/logging-errors.md
This adds the guide for error logging now that we've merged and released
the logging middleware. I'll update this guide with new logging packages
as we release them.
=> docs: add an error logging guide

.release-please-manifest.json, README.md, package-lock.json, packages/log-error/.npmignore, packages/log-error/README.md, packages/log-error/lib/index.js, packages/log-error/package.json, packages/log-error/test/lib/index.spec.js, packages/middleware-log-errors/lib/index.js, packages/middleware-log-errors/package.json, packages/middleware-log-errors/test/lib/index.spec.js, release-please-config.json
This splits out the main logging functionality from the middleware into
a new package which allows us to log handled, recoverable, and unhandled
logs consistently no matter where we need them (not just in middleware).
This means we can support more non-Express uses-cases and will massively
simplify the code in the Express middleware.
This PR includes splitting out the logging functionality and switching the
middleware to use the new functions.
This refactor has the benefit of resolving [FTDCS-192](https://financialtimes.atlassian.net/browse/FTDCS-192) 🎉
=> feat: add a log-error package

docs/getting-started/logging-errors.md
This reorganises the error logging documentation now that we have the
log-error module and have a codified way of logging recoverable errors.
=> docs: outline how to log recoverable errors

.github/dependabot.yml, docs/contributing.md
This means that Dependabot should now keep the individual packages up to
date as well as the central dev dependencies.
=> chore: add dependabot config for packages

package-lock.json, packages/log-error/package.json
n-logger v10.2.0 adds in the ability to switch to Heroku log drains
rather than sending logs to Splunk manually. In order to support this
feature we need to limit the version range to be v10.2.0 or above
otherwise the feature will be present inconsistently.
This is not a breaking change because the major versions of n-logger
between 6 and 10 have no impact on this package:
- v7.0.0 of n-logger only supports Node.js 14+ (no change for us)
- v8.0.0 of n-logger re-adds support for Node.js 12
- v9.0.0 of n-logger deprecates the SYSTEM_CODE environment variable
(but then undeprecates it in v9.0.1)
- v10.0.0 of n-logger only supports Node.js 14+ (no change for us)
=> feat: require n-logger v10.2.0

packages/log-error/README.md, packages/log-error/lib/index.js, packages/log-error/test/lib/index.spec.js, packages/middleware-log-errors/README.md
n-logger seems to expect a message field when logging, so we're now
providing a human-readable short summary of the error message in this
field. This does duplicate some data but will make error logs much
easier to quickly analyse in Splunk (the `error` property is collapsed
by default).
I decided to use both the error name and message so that you can also
tell if you're dealing with an operational error at a quick glance:
```
OperationalError: something expected went wrong
Error: something unexpected went wrong
```
**Note for reviewing:** there are a lot of changes in the tests because
every instance of a log call had to change to cater for the new message
property. We also had to make our mock serialised error into a proper
object so that we could test with and without certain …
=> feat: log an error summary in the message property

package-lock.json, package.json, packages/log-error/CHANGELOG.md, packages/middleware-log-errors/CHANGELOG.md, release-please-config.json
This is annoying, but I dug into the code for Release Please and it gets the manifest config directly from GitHub rather than the local file so our change needs to be merged into `main` before we can progress beyond Release Please v13.18.6.
This addresses the broken changelog files and also makes sure we're using a version of Release Please that works.
=> Fix release please

docs/getting-started/handling-errors.md
This PR applies a documentation revision that came out of [this Slack discussion](https://financialtimes.slack.com/archives/CPNKK12S1/p1659013086713049?thread_ts=1659003590.492259&cid=CPNKK12S1):
> @andygout: In the last example in [handling errors](https://github.com/Financial-Times/dotcom-reliability-kit/blob/main/docs/getting-started/handling-errors.md), is there a specific reason to not include any information from the caught `error` in the `OperationalError` instance? E.g. to give information about why the fruit API did not return a stock level for a given ID
> @rowanmanning: Nope, I think that’s actually an issue so if you fancy opening a PR to address this then I’d happily review! I’d probably check the status code and error message and include it in the new operational error …
=> Modify handling recoverable errors example

packages/log-error/README.md, packages/log-error/lib/index.js, packages/log-error/test/lib/index.spec.js, packages/middleware-log-errors/README.md
This adds new app-related properties to error logs. We decided these
would be useful to help us debug issues and will bring logs in Splunk
closer to Sentry in terms of the information they hold.
These are the added properties:
- `app.commit`: set to `process.env.HEROKU_SLUG_COMMIT`
- `app.nodeVersion`: set to `process.versions.node`
- `app.releaseDate`: set to `process.env.HEROKU_RELEASE_CREATED_AT`
Some of these rely on the Heroku Dyno Metadata labs feature but we
recommend use of this in all our apps anyway:
https://devcenter.heroku.com/articles/dyno-metadata
**Note to reviewers:** most of the changes here are to the tests, which
all need to be updated when we add new properties to fields. I think the
tests themselves need less of a review as it's a lot of repetition.
This resolves …
=> feat: add new app properties to error logs

docs/getting-started/handling-errors.md, docs/getting-started/throwing-errors.md, packages/errors/README.md, packages/errors/lib/operational-error.js, packages/errors/test/lib/operational-error.spec.js, packages/serialize-error/README.md, packages/serialize-error/lib/index.js, packages/serialize-error/test/lib/index.spec.js
FTDCS-250
Jira card: https://financialtimes.atlassian.net/jira/software/c/projects/FTDCS/boards/1426?modal=detail&selectedIssue=FTDCS-250
> **Rowan Manning:** @andygout [pointed out](https://financialtimes.slack.com/archives/CPNKK12S1/p1659013086713049?thread_ts=1659003590.492259&cid=CPNKK12S1) in one of my examples for handling errors we lose some information about the original error. I’ve had a potential solution in mind for this for a while and it’s worth getting down on paper.
> I think that OperationalError should have a new first-class property named cause. This expects another Error object and marks that error as the root cause of the operational error. This will allow us to use generic messages in some places but still capture the original error information. Using the example from …
=> feat: add OperationalError cause property

docs/getting-started/throwing-errors.md, packages/errors/README.md, packages/errors/test/lib/operational-error.spec.js, packages/serialize-error/README.md, packages/serialize-error/lib/index.js, packages/serialize-error/test/lib/index.spec.js
When doing the work in this PR https://github.com/Financial-Times/dotcom-reliability-kit/pull/98, I noticed that the `relatesToSystems` property was missing from some documentation, JSDocs, and tests.
This PR includes it in those places.
=> chore: additional relatesToSystems documentation and tests

.github/dependabot.yml, .release-please-manifest.json, examples/express/app.js, examples/express/package.json, examples/express/test/index.spec.js, package-lock.json, packages/middleware-render-error-info/.npmignore, packages/middleware-render-error-info/README.md, packages/middleware-render-error-info/lib/index.js, packages/middleware-render-error-info/package.json, packages/middleware-render-error-info/test/lib/__snapshots__/index.spec.js.snap, packages/middleware-render-error-info/test/lib/index.spec.js, release-please-config.json
This makes a start on FTDCS-184, adding a new middleware function which
renders an error information page for debugging. This is the absolute
bare-bones of the module so far and it only provides some basic error
information.
There are also some unanswered questions, mostly whether this will play
nicely with the n-raven and n-express error handlers. I think this will
need some testing once we have a basic 0.1.0 release of this package.
This does not include documentation yet, I think I'd rather work on that
once we've nailed down exactly what the behaviour is and whether we
include any config options.
The commit is tagged to release as 0.1.0, so this should be OK to merge
even though it's incomplete. That way we'll all be able to incrementally
add features rather than having a long-running …
=> feat: add a middleware-render-error-info package

package-lock.json, packages/middleware-render-error-info/lib/index.js, packages/middleware-render-error-info/lib/render-error-page.css, packages/middleware-render-error-info/lib/render-error-page.js, packages/middleware-render-error-info/lib/render-layout.js, packages/middleware-render-error-info/package.json, packages/middleware-render-error-info/test/lib/__snapshots__/index.spec.js.snap, packages/middleware-render-error-info/test/lib/index.spec.js
This adds all the error information we need to the error info page. It
also introduces styling via Origami and some help text to explain to
engineers what each piece of error information is for.
I'm looking for general feedback on:
* The approach. We agreed we'd like to avoid a build step or lots
of additional dependencies. Is this approach still what we want
now that we have some code to look at?
* Is there any more useful (and easy to get hold of) information
that we might want to display on this page?
* Do we want to try and tackle `error.stack` parsing as part of
this PR? Or should we aim to get this merged and add as a
later feature?
We could possibly move each of the `renderX` methods into their
own files, but this might be overkill. For now I split out the layout
as it's mostly …
=> feat: render full error information

README.md, packages/middleware-render-error-info/README.md, packages/middleware-render-error-info/package.json
This covers the basics and includes a screen grab. This is quite light
on the ground because the actual API for this module is super small.
Resolves FTDCS-265.
=> docs: add README for middleware-render-error-info

release-please-config.json
This is part 1 of a fix, and it's down to me misconfiguring Release Please quite early on. We don't want `chore` commits to trigger a release and this will address that.
=> chore: don't trigger releases for chores

docs/contributing.md
The `docs` commit prefix _does_ trigger a patch release
which I think is what we want (docs changes should make
it to npm right?)
[Evidence: see `docs` isn't hidden in the config](https://github.com/Financial-Times/dotcom-reliability-kit/blob/main/release-please-config.json#L4-L23).
=> docs: correct a mistake in commit type prefixes

packages/middleware-render-error-info/lib/render-error-page.js, packages/middleware-render-error-info/test/unit/lib/__snapshots__/index.spec.js.snap, packages/middleware-render-error-info/test/unit/lib/index.spec.js
FTDCS-274
Jira card: https://financialtimes.atlassian.net/jira/software/c/projects/FTDCS/boards/1426?modal=detail&selectedIssue=FTDCS-274
> We realised after building it that it’s very easy in [middleware-render-error-info](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/middleware-render-error-info#readme) to forget that it’s displaying sensitive information. It’s reasonable to think that someone might share a screen-grab of this page while debugging something and that’s an issue if we display things like API keys or cookie values in the clear.
> I think there are a few options with different levels of difficulty:
> - Obfuscate the value for these fields (we’d need to decide on a list, and I’m sure we could miss some sensitive headers). We could do this by …
=> feat: conceal sensitive values in middleware-render-error-info display

.github/dependabot.yml
I think we're getting these at night, I wonder if it's
better if it runs first thing – I often use the first half
hour of the day for chores like dependency bumps.
=> chore: set a time and timezone for Dependabot

.circleci/config.yml, examples/express/package.json, logos/package.json, package-lock.json, package.json, packages/errors/package.json, packages/log-error/package.json, packages/middleware-log-errors/package.json, packages/middleware-render-error-info/package.json, packages/serialize-error/package.json, packages/serialize-request/package.json
Node.js 18 isn't in active Long-Term-Support yet, but I think it's worth
starting to test against it as it becomes an LTS version of Node.js in
October 2022. This ensures that once we're ready to move apps to v18 our
modules will work as expected.
=> chore: start testing in Node.js 18

packages/log-error/README.md, packages/middleware-log-errors/README.md
We weren't being very clear that the `X-Request-ID` header is already
automatically logged under the `request.id` property. I've attempted to
clarify this in the documentation.
If this is still not clear then another option would be to ignore this
header if it's passed in as part of the `includeHeaders` option.
@gyss I updated this documentation based on the inclusion of the
`X-Request-ID` header [here](https://github.com/Financial-Times/dotcom-pages/pull/5#discussion_r945760738). Do you think it's clearer now / you would
have known there was no need to include it?
=> docs: clarify that x-request-id is auto-logged

docs/getting-started/handling-errors.md, docs/getting-started/throwing-errors.md, packages/errors/README.md, packages/errors/lib/data-store-error.js, packages/errors/lib/index.js, packages/errors/lib/upstream-service-error.js, packages/errors/lib/user-input-error.js, packages/errors/test/unit/lib/data-store-error.spec.js, packages/errors/test/unit/lib/index.spec.js, packages/errors/test/unit/lib/upstream-service-error.spec.js, packages/errors/test/unit/lib/user-input-error.spec.js
This adds some new error classes to the `errors` package which should
help apps provide more detailed error information with relatively little
effort. It adds in:
* `DataStoreError`
* `UpstreamServiceError`
* `UserInputError`
I based these on [the needs of next-home-page](https://github.com/Financial-Times/next-home-page/blob/main/apps/home-page/lib/errors.ts), one of our more
recently-built apps which does error handling quite well. I also did
some digging across all of [the FT's repos](https://cs.github.com/?q=extends+Error+%28language%3AJavaScript+OR+language%3ATypeScript%29&scope=org%3AFinancial-Times&scopeName=Financial-Times) to get an idea of what error
classes our apps are defining themselves.
Resolves FTDCS-285.
=> feat: add new more specific error classes

docs/getting-started/handling-errors.md, packages/errors/README.md, packages/errors/lib/upstream-service-error.js, packages/errors/test/unit/lib/upstream-service-error.spec.js
We agreed that a 502 is a more sensible default than a 500
- https://github.com/Financial-Times/dotcom-debug-user/pull/139#discussion_r946863853
- [Slack](https://financialtimes.slack.com/archives/CPNKK12S1/p1660661442019349)
=> fix: default UpstreamServiceError to HTTP 502

packages/middleware-log-errors/lib/index.js, packages/middleware-render-error-info/lib/index.js
We're looking into Open Telemetry at the moment and realised that
unnamed functions (especially as middleware) make it difficult to follow
traces easily. This addresses the only places we're currently using
anonymous functions.
=> fix: return named functions in middleware

.github/dependabot.yml
I extracted this from #143 where it was added by mistake.
This ensures that the Express example has dependencies
updated too.
=> chore: add a dependabot config for Express example

.release-please-manifest.json, README.md, examples/express/index.js, examples/express/package.json, package-lock.json, packages/app-info/.npmignore, packages/app-info/README.md, packages/app-info/lib/index.js, packages/app-info/package.json, packages/app-info/test/unit/lib/index.spec.js, packages/log-error/lib/index.js, packages/log-error/package.json, packages/log-error/test/unit/lib/index.spec.js, packages/middleware-render-error-info/lib/index.js, packages/middleware-render-error-info/lib/render-error-page.js, packages/middleware-render-error-info/lib/render-layout.js, packages/middleware-render-error-info/package.json, packages/middleware-render-error-info/test/unit/lib/index.spec.js, release-please-config.json
This tucks away nearly all of our environment variable access into a new
module named app-info. This means we're no longer repeating some logic
across the other modules and can remove a lot of tests (despite adding a
new package and a bunch of documentation, this decreases the overall
lines of code by ~60).
This also adds a feature: we're now not only looking at the
`SYSTEM_CODE` environment variable, we're also attempting to load the
`package.json` file in the current working directory and normalising the
name to get a default system code. This nearly* matches the behaviour in
n-express.
A benefit of this work is that if we need to use the system code in
other places (which I think is likely, e.g. if we wrap any of the
tooling for OpenTelemetry). We could also replace usage of all these …
=> fix: refactor to centralise environment variables

.circleci/config.yml
v18.8.0 was released last week and the CircleCI image is now available.
=> chore: bump Node.js 18 to the latest version

docs/design.md
I saw [this decision document](https://financialtimes.atlassian.net/l/cp/cUUXy7Gx) on API Rationalisation and realised that
maybe we hadn't clarified our choice of CommonJS. I can see it coming up
in future so I decided to write up my original thoughts.
This can change in future, but think it's worth documenting why things
are the way they are!
=> docs: clarify our decision to write CommonJS

docs/design.md
Oops I missed this. I also think a heading of JavaScript
makes more sense.
=> docs: correct the design guide ToC

packages/middleware-log-errors/README.md, packages/middleware-render-error-info/README.md
This bolds and highlights that middleware order matters, which should result in less confusion about where to mount the middleware. It also adds a short explanation of _why_ the order matters, rather than just dictating a rule without explanation.
It looks like this:
=> docs: clarify middleware mounting order

packages/app-info/lib/index.js, packages/app-info/test/unit/lib/index.spec.js, packages/errors/lib/data-store-error.js, packages/errors/lib/http-error.js, packages/errors/lib/index.js, packages/errors/lib/operational-error.js, packages/errors/lib/upstream-service-error.js, packages/errors/lib/user-input-error.js, packages/errors/test/unit/lib/data-store-error.spec.js, packages/errors/test/unit/lib/http-error.spec.js, packages/errors/test/unit/lib/index.spec.js, packages/errors/test/unit/lib/operational-error.spec.js, packages/errors/test/unit/lib/upstream-service-error.spec.js, packages/errors/test/unit/lib/user-input-error.spec.js, packages/log-error/lib/index.js, packages/log-error/test/unit/lib/index.spec.js, packages/middleware-log-errors/lib/index.js, packages/middleware-log-errors/test/unit/lib/index.spec.js, packages/middleware-render-error-info/lib/index.js, packages/middleware-render-error-info/test/unit/lib/index.spec.js, packages/serialize-error/lib/index.js, packages/serialize-error/test/unit/lib/index.spec.js, packages/serialize-request/lib/index.js, packages/serialize-request/test/unit/lib/index.spec.js
We messed up here, and we didn't consider the use case of TypeScript written as ES Modules being compiled to CommonJS modules. When using the import signature:
```
import example from 'example';
```
the JavaScript compiled from the above TypeScript will always look for the `default` property on the module. This is different from Node.js native ESM which is what we tested with.
The solution is to alias `module.exports` as `module.exports.default` which ensures that this works in the same way for native ESM as well as compiled JavaScript from TypeScript.
=> fix: make sure that ESM + TypeScript works

docs/getting-started/handling-errors.md, docs/getting-started/logging-errors.md, docs/getting-started/throwing-errors.md, packages/log-error/README.md, packages/middleware-log-errors/README.md, packages/middleware-render-error-info/README.md
GitHub has supported special rendering of note and warning messages in Markdown for a while based on [this discussion](https://github.com/community/community/discussions/16925).
It's nice to have it consistently rendered like this so I've switched out the markup across all our documentation.
Here are some example screen shots from the docs:
=> docs: use GitHub's note/warning highlights

.circleci/config.yml, .gitignore, docs/contributing.md, docs/design.md, jsconfig.build.json, jsconfig.json, package.json, packages/app-info/lib/index.js, packages/errors/lib/data-store-error.js, packages/errors/lib/http-error.js, packages/errors/lib/index.js, packages/errors/lib/operational-error.js, packages/errors/lib/upstream-service-error.js, packages/errors/lib/user-input-error.js, packages/log-error/lib/index.js, packages/middleware-log-errors/lib/index.js, packages/middleware-render-error-info/lib/index.js, packages/middleware-render-error-info/lib/render-error-page.js, packages/middleware-render-error-info/lib/render-layout.js, packages/serialize-error/lib/index.js, packages/serialize-request/lib/index.js, scripts/create-package.js
This ensures that when we publish to npm, we generate and include TypeScript type declarations (`.d.ts`) with our modules. These are generated from the JSDoc and map 1:1 with what we've written. It's annoying that we had to do this but I think it makes the most sense when you consider the alternatives.
@jamesr101 spotted today that with a full TypeScript-based projects, he was getting type errors and no type hinting in VSCode. I tried a basic TypeScript project and it works fine unless you start configuring with a `tsconfig.json` file. Once you add that in, type hinting in VSCode seems to break. This is why we haven't spotted this before – our initial testing was too basic.
I found out that this is a known issue and that JavaScript-based projects which use JSDoc types are not actually …
=> Publish TypeScript type definitions

packages/app-info/.npmignore, packages/errors/.npmignore, packages/log-error/.npmignore, packages/middleware-log-errors/.npmignore, packages/middleware-render-error-info/.npmignore, packages/serialize-error/.npmignore, packages/serialize-request/.npmignore, scripts/create-package.js
This is annoying. I forgot that `.npmignore` also uses `.gitignore` rules and so our TypeScript files were being ignored.
=> fix: include TypeScript types in the build

packages/errors/lib/http-error.js
When trying to use the dotcom-reliability-kit/errors in a TS project, I was getting a build error saying "'readonly' modifier can only appear on a property declaration".  
See below for the full error I was getting in my TS project. I was also getting the same error from VSCode in the `http-error.d.ts` file.
```
➜  n-membership-sdk git:(ACC-1965-using-upstreamError) ✗ make build            
./node_modules/.bin/tsc --declaration
node_modules/@dotcom-reliability-kit/errors/lib/http-error.d.ts:8:12 - error TS1024: 'readonly' modifier can only appear on a property declaration or index signature.
8     public readonly get status(): number;
~~~~~~~~
Found 1 error.
make: *** [build] Error 2
```
`get status()` is not a property, so it doesn't make sense for it to be readonly, and should be …
=> fix(errors): removes readonly JDoc property from getter

jsconfig.json, packages/errors/lib/data-store-error.js, packages/errors/lib/http-error.js, packages/errors/lib/operational-error.js, packages/errors/lib/upstream-service-error.js, packages/errors/lib/user-input-error.js
This adds in some stricter type checking which is easy to add now but more difficult to add later. Most of these are properties which can be added without having to change any Reliability Kit code, the exception being `noImplicitOverride` (see below). I think it's worth adding these in so that we catch these kinds of issues if they're ever introduced.
**`noImplicitOverride`:** This option requires you to acknowledge when you're overriding a property or method on a parent class. This ensures that TypeScript will error if we ever change methods or properties on a base class but miss any extending classes. It requires that we add an `@override` tag to extended class members and I've added these.
[Documentation for all of these options is here](https://www.typescriptlang.org/tsconfig).
=> Add stricter type checking

.github/dependabot.yml, .release-please-manifest.json, docs/getting-started/logging-errors.md, package-lock.json, packages/crash-handler/.npmignore, packages/crash-handler/README.md, packages/crash-handler/lib/index.js, packages/crash-handler/package.json, packages/crash-handler/test/unit/lib/index.spec.js, release-please-config.json
This is the basic functionality for an uncaught exception handler. We're going with a single option for now so that you can pass the process in (e.g. for binding to a child process).
I decided against adding an `exitCode` or `onError` option as outlined in the issue, because I think we shouldn't add things unless our teams have demostrated a need for them.
Resolves #225.
=> feat: add an uncaught exception handler

.github/dependabot.yml
This configures Dependabot to use the `fix:` commit prefix for production dependencies by default and `chore:` for development dependencies. Right now it's defaulting to `chore:` for everything which is incorrect as chores do not trigger releases.
This stops us from having to manually override the commit message so often, though we'll still need to do this if we decide that the dependency bump is either a feature or breaking change.
=> chore: configure Dependabot to use fix commits

.github/dependabot.yml, .release-please-manifest.json, jsconfig.build.json, jsconfig.json, package-lock.json, packages/logger/.npmignore, packages/logger/README.md, packages/logger/docs/migration.md, packages/logger/lib/index.js, packages/logger/lib/logger.js, packages/logger/package.json, packages/logger/test/end-to-end/compatibility-test-cases.js, packages/logger/test/end-to-end/compatibility.spec.js, packages/logger/test/end-to-end/helpers/clean-log-for-testing.js, packages/logger/test/end-to-end/helpers/find-log-with-property-value.js, packages/logger/test/end-to-end/helpers/split-and-parse-json-logs.js, packages/logger/test/end-to-end/scripts/run-loggers-with-test-case.js, packages/logger/test/unit/lib/index.spec.js, packages/logger/test/unit/lib/logger.spec.js, release-please-config.json
> **Note**
> This is an experimental piece of work which may never make it into production. There's no agreed timeline for migrating things to this new logger - we want to be careful about introducing too many Reliability Kit migrations at once.
This adds a new experimental package which aims to be a near drop-in replacement for n-logger and a replacement for n-serverless-logger with a little work. I spent a lot of time working on a suite of end-to-end tests to ensure that it's as compatible as possible.
I think the next step will be to release a beta version of this package (v0.1.0) so that we can test it in some non-critical applications.
I tried to approach the build of this in the same way I would a package that'd definitely go into production, because writing tests and documentation …
=> feat: add an experimental logger package

packages/logger/README.md, packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js
This adds an option to specify log transforms - functions which can modify log data before it's sent. This is a foundational piece of work which is needed in order for us to provide feature parity with n-mask-logger.
A later piece of work will introduce a log transform which masks fields in exactly the same way as n-mask-logger.
=> feat: add the ability to transform log data

packages/serialize-request/lib/index.js
I think this fixes #269. Our types are quite restrictive, but actually it's fine to pass in an object which looks vaguely like a request (has `headers`, `method`, and `url` properties). @apaleslimghost does this look like it'll fix your issue?
The easiest way to test might be for you to drop the generated types file into your project's `node_modules/@dotcom-reliability-kit/serialize-request/lib` folder and verify that you no longer have issues:
```ts
export = serializeRequest;
declare function serializeRequest(request: string | Request, options?: SerializeRequestOptions | undefined): SerializedRequest;
declare namespace serializeRequest {
export { exports as default, ExpressRequest, HttpIncomingMessage, BasicRequest, Request, SerializeRequestOptions, SerializedRequestHeaders, …
```
=> fix: loosen serialize-request type requirements

package-lock.json, packages/logger/README.md, packages/logger/lib/logger.js, packages/logger/package.json, packages/logger/test/unit/lib/logger.spec.js
This adds the ability for an app using the new logger to see prettified logs locally, which makes issues easier to debug. We configure pino-pretty if it's present to work with our logs.
This resolves #281. I decided against adding extra options to disable prettification, as teams can manually set their `NODE_ENV` to `production` if they want to inspect the raw JSON output.
The issue linked above contains more information on why I decided to solve this within the logger rather than externally or with Tool Kit.
=> feat: add prettification to logs in local dev

packages/errors/lib/index.js, packages/log-error/lib/index.js
This commit 8cdd4d74afe44c51504ddf0f9a3219db3ad2654a broke the exports when used in a native ESM context. I'd rather have a little more clutter in our type definitions than not be able to import modules as our users expect. Thanks @apaleslimghost for the heads up.
I'm going to investigate whether we need automated tests to ensure that our modules behave as expected in:
* CommonJS (native)
* ESM (native)
* ESM via [Sucrase](https://sucrase.io/)
* ESM via TypeScript
* ESM via Babel???
I _really_ hate that this is the Node.js ecosystem.
=> fix: correct ESM exports

resources/splunk-dashboards/src/heroku.json
This adds a boolean to the "Common errors" panel which outlines whether each error crashed the app or not.
It looks like this:
=> feat: highlight crashing errors in the dashboard

packages/log-error/README.md, packages/middleware-log-errors/README.md, packages/serialize-request/README.md, packages/serialize-request/lib/index.js, packages/serialize-request/test/unit/lib/index.spec.js
Fixes https://github.com/Financial-Times/dotcom-reliability-kit/issues/223
I checked the request headers that we see on a locally-running app (next-static) and there were none that seemed like they would be obviously vital to include by default at this stage:
```js
[
'Host',
'Connection',
'sec-ch-ua',
'sec-ch-ua-mobile',
'sec-ch-ua-platform',
'Upgrade-Insecure-Requests',
'User-Agent',
'Accept',
'Purpose',
'Sec-Fetch-Site',
'Sec-Fetch-Mode',
'Sec-Fetch-User',
'Sec-Fetch-Dest',
'Accept-Encoding',
'Accept-Language',
'Cookie'
]
```
The [HTTP headers list](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) provided by MDN is naturally very extensive, suggesting that perhaps the approach we take (as suggested by @rowanmanning) is to wait and see which headers teams using Reliability Kit …
=> feat: expand list of default headers included in serialized requests

.github/dependabot.yml, examples/express/package.json, package-lock.json
This is causing issues because it results in multiple versions of Reliability Kit packages being installed in the repo. This means that, when we're testing changes to the types, TypeScript gets confused about which version of a package we're actually looking at. Setting these to `*` means that we always use the local dependency.
We also set bumping dependencies in the examples to always be marked as a chore, as this should never result in an actual release.
=> fix: stop pinning dependencies in express example

packages/log-error/README.md, packages/middleware-log-errors/README.md, packages/serialize-request/README.md, packages/serialize-request/lib/index.js, packages/serialize-request/test/unit/lib/index.spec.js
This resolves #222, exposing the default headers that we use in `serializeRequest`. This should reduce the need for repetition across our apps as they can destructure this into their own `includeHeaders` config.
I decided to go for the uppercase "constant-style" naming with `DEFAULT_INCLUDED_HEADERS`. I also froze the exported object to avoid potential side-effects.
=> feat: expose the default serialized headers

packages/logger/lib/index.js
This should address another issue that Kara spotted, where we're not properly defining types in this logger entrypoint.
=> fix: add proper types for the default logger

packages/crash-handler/README.md, packages/crash-handler/lib/index.js, packages/crash-handler/test/unit/lib/index.spec.js, packages/log-error/README.md, packages/log-error/lib/index.js, packages/log-error/test/unit/lib/index.spec.js, packages/middleware-log-errors/README.md, packages/middleware-log-errors/lib/index.js, packages/middleware-log-errors/test/unit/lib/index.spec.js
Setting a custom logger is essential for teams who use log masking or their app relies on other custom logging (e.g. their logger must include certain base data).
This is more complex than I originally thought, as we can no longer trust the logging methods that we're using. Because of this I'm now wrapping all our error logging in a try/catch so that we can fall back to logging via `console.log` which is guaranteed to work. This is a similar approach to @reliability-kit/logger.
This resolves #221.
Log masking:
```js
const {logRecoverableError} = require('@dotcom-reliability-kit/log-error');
const MaskLogger = require('@financial-times/n-mask-logger');
logRecoverableError({
error: new Error('Oops'),
logger: new MaskLogger()
});
```
Adding base data:
```js
const {logRecoverableError} = …
```
=> feat: add the ability to set a custom logger

.github/dependabot.yml, examples/serverless/.gitignore, examples/serverless/README.md, examples/serverless/handler.js, examples/serverless/package.json, examples/serverless/serverless.yml, jsconfig.json, package-lock.json
This example shows how Reliability Kit can be used in a Serverless framework app which is deployed to AWS Lambda.
It is not deployable in its current state because of the way the monorepo manages package-lock.json and node_modules. In order for it to be deployable, we would need to make a directory which contains a node_modules/ with every dependency (and its tree) that the Lambda requires.
---
Questions:
- I don't understand the lint/type failures, although I can reproduce them locally. They're running against `node_modules/url/url.js`. `node_modules/url/` was introduced as part of the Express example a long time ago 🤯 
- When I run `npm install` locally from the root, I do get a `node_modules/` in `examples/serverless` which is correctly gitignored. That modules directory only contains …
=> docs: add a serverless (Lambda) example

packages/app-info/README.md, packages/app-info/lib/index.js, packages/app-info/test/unit/lib/index.spec.js
This increases Reliability Kit's usefulness in an AWS environment, falling back to AWS and more generic variable names if the Heroku environment variables are not present. We can do this relatively easily for region, release version, and commit hash.
[Documentation on these environment variables is here](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime).
=> feat: use AWS environment variables in app-info

packages/middleware-render-error-info/test/unit/lib/__snapshots__/index.spec.js.snap, packages/middleware-render-error-info/test/unit/lib/index.spec.js
This test contains the current year for the copyright in the footer. The year changes every year so we should stub it.
=> fix: use fake timers in middleware rendering snapshot test

examples/serverless/handler.js, examples/serverless/package.json, package-lock.json
This switches the Serverless example to use the Reliability Kit logger rather than n-serverless-logger, now that it's stable.
=> docs: use the new logger in serverless example

docs/getting-started/handling-errors.md, docs/getting-started/logging-errors.md, docs/getting-started/setup.md, docs/getting-started/throwing-errors.md
The getting started guide was quite Express-centric. I've added in examples using AWS Lambda/Serverless and made the language a lot more friendly to non-Express apps.
Resolves [CPREL-478](https://financialtimes.atlassian.net/browse/CPREL-478)
[CPREL-478]: https://financialtimes.atlassian.net/browse/CPREL-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: make the user guide less Express-centric

packages/middleware-log-errors/README.md, packages/middleware-log-errors/lib/index.js, packages/middleware-log-errors/test/end-to-end/fixtures/app.js, packages/middleware-log-errors/test/end-to-end/index.spec.js, packages/middleware-log-errors/test/unit/lib/index.spec.js
This allows an app to tell the error logging middleware not to log for specific errors or requests. I think this is required for us to use the error logging middleware in next-api because [it filters out certain logs based on which app has made the request](https://github.com/Financial-Times/next-api/blob/0a700435124f5c30b6b52d333acb2f1e28e0c6a8/server/utils/log-app-error.js#L8).
Without a filter for these errors we'll see a dramatic noisy increase in next-api logs
I don't want this option to start being used frequently across our apps so there's a warning in the README. I'm also sending further logs if someone misconfigures the option so that we have visibility if an app has broken logging due to use of this feature.
=> feat: add filter option to the logging middleware

packages/middleware-log-errors/README.md
The table-of-contents wasn't updated in the PR which added the filter option. This adds a link to that section.
=> docs: update the table of contents

packages/errors/lib/data-store-error.js, packages/errors/lib/http-error.js, packages/errors/lib/operational-error.js, packages/errors/lib/upstream-service-error.js, packages/errors/lib/user-input-error.js
This is preparatory work to make sure that #438 can be completed easily without copying a lot of complex types around.
We move the union of the `Record<string, any>` type into the `OperationalErrorData` type itself which massively simplifies the types in the constructors for all the other errors.
=> fix: simplify and tidy up the error types

packages/errors/README.md, packages/errors/lib/data-store-error.js, packages/errors/lib/http-error.js, packages/errors/lib/operational-error.js, packages/errors/lib/upstream-service-error.js, packages/errors/lib/user-input-error.js, packages/errors/test/unit/lib/data-store-error.spec.js, packages/errors/test/unit/lib/http-error.spec.js, packages/errors/test/unit/lib/operational-error.spec.js, packages/errors/test/unit/lib/upstream-service-error.spec.js, packages/errors/test/unit/lib/user-input-error.spec.js
In Node.js 18, the constructor signatures for errors have changed to [support setting both a message and options](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error).
Our custom errors did not support this new constructor signatures, this work ensures that they work in the same way as Node.js 18 native errors. See issue #438 for more information.
We now support the following signatures:
```diff
new OperationalError();
new OperationalError(message);
new OperationalError(options);
+ new OperationalError(message, options);
```
This PR resolves #438.
As part of this work, I found that a limitation of TypeScript + JSDoc is that you can't document multiple different overloads for the same method. In TypeScript you can [write the following to document …
=> feat: support Node.js 18 error signatures

jsconfig.json
This option causes issues when we upgrade to TypeScript 5.0. Removing it relaxes object types a little, making it valid to pass `undefined` when an object has an optional property. I think this is generally better as it allows a user to do things like
```js
registerCrashHandler({
logger: process.env.USE_ANOTHER_LOGGER ? newLogger : undefined
});
```
=> chore: disable exactOptionalPropertyTypes

packages/serialize-request/lib/index.js
It's invalid to reassign the `exports` global and it doesn't work as expected. I think this has only not been spotted because nobody is depending on the request serializer directly.
I only spotted this because TypeScript 5.0 can now detect this issue. So this PR blocks us being able to upgrade.
=> fix: correct a broken exports

packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js
- We run our pre-production systems using a `NODE_ENV` value of `test`
- The logger only activates `pino` pretty log output when the NODE_ENV is `development`
- Swapped the check for **equals**`"development` for **not-equal** `production`
- Added an extra test for `test` and adjusted the existing `development` and `production` tests
---
Resolves #476
=> feat: allow for NODE_ENV that is not "production" or "development"

resources/splunk-dashboards/README.md, resources/splunk-dashboards/src/crashes.json
This adds a dashboard to get visibility of crashing errors across all apps which use Reliability Kit. It's similar to the Heroku dashboard that we already have but with a focus on crashes (`UNHANDLED_ERROR` events) across all apps.
You can apply a filter if you need to limit to a specific team or group.
[You can see the live dashboard here](https://financialtimes.splunkcloud.com/en-US/app/search/reliability_kit_crashes).
=> feat: add a crashing errors dashboard

packages/logger/README.md, packages/logger/lib/logger.js, packages/logger/test/end-to-end/compatibility-test-cases.js
This resolves #489. We were not matching n-logger in the way it serialized functions and this resulted in errors. We now match n-logger and just ignore any function properties.
I did this using the [`lossy` option of ungap's structured-clone](https://github.com/ungap/structured-clone#extra-features), which offers a few features over the native structured clone. The `lossy` option makes the clone behave more like `JSON.stringify`, ignoring properties that it can't serialize rather than throwing an error. Once Reliability Kit drops Node.js 16 support we can reassess this and perhaps move to native `structuredClone`.
=> fix: match n-logger's function serialization

packages/logger/docs/migration.md
=> docs: explain incompatibilities with proxy objects

docs/contributing.md
I missed this earlier, this is the process we used to tag up prerelease versions of the other packages.
=> docs: add note on how to hard-code release version

.circleci/config.yml, docs/getting-started/setup.md, package-lock.json, package.json, packages/app-info/package.json, packages/crash-handler/package.json, packages/errors/package.json, packages/log-error/package.json, packages/logger/package.json, packages/middleware-log-errors/package.json, packages/middleware-render-error-info/package.json, packages/serialize-error/package.json, packages/serialize-request/package.json, resources/logos/package.json
If your apps are using Node.js 16 or above then it's safe to immediately migrate to the new major versions of Reliability Kit packages. There are no code changes in this release.
=> chore!: drop support for Node.js 14

package-lock.json, packages/eslint-config/package.json
This adds eslint as a peer dependency, because otherwise we get some incompatibilities when installing within a repo. I just tested in dotcom-debug-user and got some cryptic errors because it wasn't using the latest version of ESLint.
I didn't consider this when reviewing the original PR :)
By adding a peerDependency of `eslint@8.27.0` we ensure that all the rules we specify actually exist within the app's installed version of ESLint. The one that immediately threw an error in dotcom-debug-user was https://eslint.org/docs/latest/rules/no-new-native-nonconstructor
Peer dependencies are designed for this case. They're meant to be used when a module _requires_ that it's installed alongside a specific version of another module. There's a good blog post on the subject here if not familiar: …
=> fix: add eslint as a peer dependency

.eslintrc.json
PR #523 bumped the ESLint JSDoc plugin from v41 to v43. I assumed a breaking change in v43 wouldn't impact us but it does. https://github.com/gajus/eslint-plugin-jsdoc/releases/tag/v43.0.0
We need to change this configuration to continue enforcing the rule that there's a line break between a JSDoc description and the tags. I'm not super attached to this rule but I think maybe updating the config to reflect our current code is better than removing the line break from all functions and creating noise in the diffs.
Before this change we were getting hundreds of ESLint warnings.
=> chore: fix the JSDoc linting after the last major

packages/logger/README.md, packages/logger/lib/logger.js, packages/logger/test/end-to-end/compatibility-test-cases.js, packages/logger/test/unit/lib/logger.spec.js
PR for GitHub issue [#480](https://github.com/Financial-Times/dotcom-reliability-kit/issues/480).
[Jira ticket](https://financialtimes.atlassian.net/browse/CPREL-527)
Changes:
- Add an additional check in the logger file that checks if the parsed error item is an instance of Error AND has a sub-property of `error`, then serialize it.
Testing:
- Fixed e2e tests and all passing now
- Added a new unit test to get back to 100% coverage
To-Do:
Nil
---
Resolves: #480
=> feat: serialize errors passed to the logger as object properties so that error information is not lost

packages/logger/README.md, packages/logger/lib/logger.js, packages/logger/test/end-to-end/scripts/run-loggers-with-test-case.js, packages/logger/test/unit/lib/logger.spec.js
This resolves #474 by allowing an application to completely disable the internal log prettification. We now allow setting a `withPrettifier` option to `false`. This is also possible with a new environment variable named `LOG_DISABLE_PRETTIFIER`.
This is also required before I can properly work on #516.
=> feat: allow disabling log prettification

package-lock.json, packages/logger/package.json
I've gone through versions and verified that Reliability Kit logger works with pino-pretty v7+. pino-pretty v6 does not work with Reliability Kit and never has.
This means that v2.2.0 of the logger is no longer a breaking change for some applications and will not give them pointless warnings.
=> fix: widen the pino-pretty version range

.eslintrc.json, package-lock.json, packages/middleware-render-error-info/test/unit/lib/index.spec.js
This uncovered one issue in some of our tests where we were setting a duplicate key.
=> chore: use the new ESLint config

package-lock.json, packages/eslint-config/lib/index.js, packages/eslint-config/package.json
Because the ESLint config isn't in a file named `.eslintrc` or similar, it doesn't get type-hinting in VSCode and we're also not certain that the configuration is valid.
We already run type checking against the code with TypeScript, so we can validate our ESLint config the same way.
=> chore: add type checking to the ESLint config

packages/serialize-request/lib/index.js, packages/serialize-request/test/unit/lib/index.spec.js
In certain contexts like Apollo Server's requestDidStart and the Headers object used by the fetch API, HTTP headers are represented as iterables rather than objects. As a result, when serializing headers for these types of requests, extra code is required to convert the iterable headers into an object.
This PR update the serializeRequest method to support iterable headers directly. The necessary changes include updating the types and modifying the code to check if the provided headers are iterable using Symbol.iterator. If the headers are iterable, they will be processed accordingly. This improvement will simplify the serialization process and eliminate the need for users to handle iterable headers in their own code.
Resolves #277
=> add request headers seriealization

packages/logger/lib/transforms/legacy-mask.js, packages/logger/test/unit/lib/transforms/legacy-mask.spec.js
This cropped up as a bug recently where Content Discovery were trying to log an entire Request object, which references itself. This resulted in Node.js running out of memory because we were infinitely recursing over the properties.
This is a bug that's always been present in n-mask-logger.
I've addressed the issue with my first legit use of `WeakSet` and I'm quite pleased with myself about it 😁
=> fix: address logging infinite recursion issue

package-lock.json, packages/logger/lib/logger.js, packages/logger/package.json, packages/logger/test/unit/lib/logger.spec.js
This switches out the library we use for cloning objects because the original one did not properly handle error objects, which resulted in a loss of log data. This works with Lodash as indicated by the now-passing test - we should now not lose error info.
This fixes an issue Artem was having when trying to use the `error` property of log data:
```js
logger.error({
error: new Error('...')
})
```
Resolves #611. Closes #610.
=> fix: properly clone error instances

packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js
If `log()` is called with a non-string first argument then we can't actually do anything useful with it - it's not valid based on the TypeScript types and so we should also error when we encounter this issue at runtime.
I'm throwing outside of the catch block because this is a rare occasion where we _do_ want logging to fully fail and an error to be thrown as it's a clear programmer error - the only resolution is to change the code to use a string.
An alternative would be to use a log level of `info` but avoid the deprecation message, but I think it's better to avoid this issue entirely rather than try to paper over it.
Resolves #547.
=> fix: throw an error when log level is not a string

packages/errors/test/end-to-end/__snapshots__/snapshots.spec.js.snap, packages/errors/test/end-to-end/errors.js, packages/errors/test/end-to-end/snapshots.spec.js
I wanted to do this before making any broader changes to errors in #638. This gives me more confidence that my change hasn't changed the error interfaces.
=> chore: add end-to-end tests for errors

packages/errors/lib/data-store-error.js, packages/errors/lib/http-error.js, packages/errors/lib/operational-error.js, packages/errors/lib/upstream-service-error.js, packages/errors/lib/user-input-error.js
I had a brainwave about how we could reduce the amount of code we maintain in the error classes, removing a lot of boilerplate constructor code. We now have a tiny bit more complexity in the core errors (`OperationalError` and `HttpError`) and a large amount of reduced complexity in the more specific errors (`DataStoreError`, `UpstreamServiceError`, `UserInputError`).
Shouldn't be merged until #639 is in.
=> Simplify errors

.eslintrc.json, packages/crash-handler/lib/index.js, packages/errors/lib/http-error.js, packages/errors/lib/operational-error.js, packages/log-error/lib/index.js, packages/logger/lib/logger.js, packages/logger/lib/transforms/legacy-mask.js, packages/logger/test/end-to-end/compatibility-test-cases.js, packages/logger/test/end-to-end/helpers/clean-log-for-testing.js, packages/logger/test/end-to-end/helpers/find-log-with-property-value.js, packages/logger/test/end-to-end/helpers/split-and-parse-json-logs.js, packages/middleware-log-errors/lib/index.js, packages/middleware-render-error-info/lib/render-error-page.js, packages/serialize-error/lib/index.js, packages/serialize-request/lib/index.js, resources/logos/scripts/build.js
This PR fixes the ESlint warnings for JSDoc type checking (issue #509). All the 25 warnings have been fixed 🎉 
For the `Iterable` type warning problem, this was fixed based on [github issue help](https://github.com/gajus/eslint-plugin-jsdoc/issues/280)
[JIRA](https://financialtimes.atlassian.net/browse/CPREL-650)
=> chore: eslint warnings for object type defs

packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js
Currently we're seeing errors in Content Discovery repos because they're using the logger like this:
```js
eventEmitter.on('error', logger.error);
```
This doesn't work because the log method can no longer access `this` – the method has been detached from the parent class. For better or worse, n-logger [did resolve this](https://github.com/Financial-Times/n-logger/blob/main/src/lib/logger.js#L47). I think for compatibility we should replicate this behaviour.
=> Handle log method detachment

package-lock.json, packages/crash-handler/lib/index.js, packages/log-error/README.md, packages/log-error/lib/index.js, packages/log-error/package.json, packages/log-error/test/unit/lib/index.spec.js, packages/middleware-log-errors/README.md, packages/middleware-log-errors/lib/index.js, packages/middleware-log-errors/test/end-to-end/fixtures/app.js, packages/middleware-log-errors/test/end-to-end/index.spec.js, packages/middleware-render-error-info/lib/index.js, packages/middleware-render-error-info/test/unit/lib/index.spec.js
This removes n-logger from all packages, switching it to Reliability Kit logger. To make sure that teams can undo this temporarily, I've added the ability to configure the logger to the only module where it wasn't possible - middleware-render-error-info.
This means that these modules will no longer log to Splunk unless the app they're used in is configured to forward `stdout` logs there.
n-logger is still installed as a development dependency in a few places, mostly for testing compatibility with Reliability Kit logger and also in places where we're importing n-express for end-to-end middleware tests. You can verify that n-logger is not installed as a production dependency with this:
```sh
npm ls --depth 100 --omit dev @financial-times/n-logger
```
Part of …
=> feat!: switch to Reliability Kit logger

packages/crash-handler/README.md, packages/middleware-log-errors/README.md, packages/middleware-log-errors/lib/index.js, packages/middleware-log-errors/test/unit/lib/index.spec.js, packages/middleware-render-error-info/lib/index.js
This removes all the places across Reliability Kit where we have to work around the existence of Sentry/n-raven. This is breaking because we now require the latest version of n-express which doesn't include n-raven.
Part of [CPREL-668](https://financialtimes.atlassian.net/browse/CPREL-668).
[CPREL-668]: https://financialtimes.atlassian.net/browse/CPREL-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix!: remove Sentry workarounds

packages/log-error/lib/index.js, packages/log-error/test/unit/lib/index.spec.js
Now that we've moved to Reliability Kit logger we can log unhandled errors with a level of "fatal". If the logger doesn't have a fatal method then we fall back to the error method so this can continue to work with the old loggers.
This is one step towards us using appropriate log levels in all cases across our estate and being able to more easily differentiate crashing bugs without having to know the event name.
This is breaking because our tooling (Splunk alerts / searches) will need an update.
```diff
{
+ 	"level": "fatal",
- 	"level": "error",
"time": 1691364939967,
"event": "UNHANDLED_ERROR",
"message": "Error: bind EADDRINUSE null:46492",
"error": {
"name": "Error",
"code": "EADDRINUSE",
"message": "bind EADDRINUSE null:46492",
"isOperational": false,
"relatesToSystems": [],
"cause": …
```
=> feat!: log unhandled errors with a level of "fatal"

packages/logger/lib/index.js
The types that were generated weren't working properly in TypeScript projects that imported and created a new `Logger` instance, this is because we were assigning directly to `module.exports` instead of creating a new instance of the logger and _then_ assigning it.
I generated the new type files and tested them in a TS project (n-user-api-client), they now work as expected.
=> fix: correct types for the logger

.release-please-manifest.json, package-lock.json, packages/fetch-error-handler/.npmignore, packages/fetch-error-handler/README.md, packages/fetch-error-handler/lib/create-handler.js, packages/fetch-error-handler/lib/index.js, packages/fetch-error-handler/package.json, packages/fetch-error-handler/test/unit/lib/create-handler.spec.js, packages/fetch-error-handler/test/unit/lib/index.spec.js, release-please-config.json
This introduces a new package named @dotcom-reliability-kit/fetch-error-handler. It's designed to reduce boilerplate when handling `fetch` errors and provide better debugging information when fetches fail.
There was discussion about this feature in a [discussion on GitHub here](https://github.com/Financial-Times/dotcom-reliability-kit/discussions/643). Big thanks to @AniaMakes, @phelipemaia, @vbachev, and @wheresrhys for their contributions.
There are a few key differences in the implementation:
1. We decided not to catch network and timeout errors as a first pass. `fetch` already throws errors for these and they could be added in a future version without a breaking change.
2. We decided not to try and handle JSON parsing of the body. Again we wanted to get an MVP out and then see how …
=> feat: add a fetch-error-handler package

packages/log-error/lib/index.js
This caused a bug in next-subscribe who are providing a custom logger to Reliability Kit which does not have methods bound to `this`. Because we _can_ fix this in Reliability Kit I think we should - ideally we want as few code changes as possible when teams migrate.
=> fix: stop requiring bound log methods

packages/logger/README.md
We found this issue in the FT.com home page when migrating to the Reliability Kit logger. The fix is to manually mock the logger when you're running tests using Jest. This documentation gives us something to point to if someone else encounters this issue.
Resolves #693.
=> docs: add a note on testing with Jest

packages/app-info/lib/index.js, packages/logger/test/end-to-end/compatibility.spec.js, packages/middleware-log-errors/test/end-to-end/index.spec.js, packages/middleware-render-error-info/lib/render-layout.js, resources/logos/scripts/build.js, scripts/create-package.js
GitHub Issue #527 
[JIRA](https://financialtimes.atlassian.net/browse/CPREL-706)
This PR replaces some built-in module references (e.g. path, http, child_process, fs, and fs/promises) with the `node:`-prefixed versions
=> chore: upgrades node module imports to use built in node modules

packages/log-error/lib/index.js, packages/log-error/test/unit/lib/index.spec.js
#654 
adds processType property to error logger to add extra error information when a lambda fails. 
ran `npm run tests` and all tests passed 
[Jira](https://financialtimes.atlassian.net/browse/CPREL-722)
=> feat: add processType property to error logger

.github/dependabot.yml
This will reduce the amount of PR churn in this repo by grouping together dev dependency updates into a single PR if they're a `minor` or `patch` level change. [See docs for more info on this configuration](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups).
=> chore: group dev dependency PRs together

package-lock.json, packages/fetch-error-handler/README.md, packages/fetch-error-handler/lib/create-handler.js, packages/fetch-error-handler/package.json, packages/fetch-error-handler/test/end-to-end/fixtures/app.js, packages/fetch-error-handler/test/end-to-end/index.spec.js, packages/fetch-error-handler/test/unit/lib/create-handler.spec.js
This adds in handling for most of the common errors that we see when making `fetch` requests. There's a lot of extra logic in here but I think it's worthwhile to augment these errors and throw ones with correct status codes that our engineers can immediately understand.
Due to the fact that we use a variety of different `fetch` implementations across the FT, this really isn't doable at the Splunk level: we can't reliably say "here's a search which shows every fetch request that has timed out".
Because of the amount of logic and the fact we're relying on error names and codes, this comes with a suite of end-to-end tests that allow us to verify that the following `fetch` implementations throw the expected errors. This way, if something changes, we'll see it immediately in a failing …
=> feat: handle common errors thrown by fetch

packages/serialize-request/lib/index.js, packages/serialize-request/test/unit/lib/index.spec.js
When the request URL is particularly long, Splunk events break because they're concatenated if they exceed a certain length. This causes the JSON to be invalid and so we don't parse out fields.
We probably shouldn't blindly trust the URL as it's user input. We now truncate request URLs at 200 characters and add an indicator so that it's clear in the logs when the URL was too long.
=> fix: trim long request URLs

packages/app-info/README.md, packages/app-info/lib/index.js, packages/app-info/test/unit/lib/index.spec.js
Adds a cloudProvider property which is set to either heroku or aws depending on where we think the system is hosted. To figure this out we’ll have to find some environment variables which we have high confidence are defined by only Heroku or AWS/Lambda.
We’re going to use this in the OpenTelemetry tracing.
[JIRA](https://financialtimes.atlassian.net/browse/CPREL-834)
=> feat: add cloudProvider as exported property for appInfo

packages/logger/test/end-to-end/helpers/clean-log-for-testing.js, packages/serialize-error/README.md, packages/serialize-error/lib/index.js, packages/serialize-error/test/unit/lib/index.spec.js
This helps us uniquely identify errors and gives us another data point to group errors by without resorting to very complicated Splunk logic. We're intending on using this fingerprint to help Customer Care and Operations more quickly direct us to the root cause of a problem.
You will also be able to more easily see the common errors that your application throws if you're using the Reliability Kit logging middleware.
=> feat: add a fingerprint to serialized errors

packages/middleware-render-error-info/README.md, packages/middleware-render-error-info/lib/index.js, packages/middleware-render-error-info/package.json, packages/middleware-render-error-info/test/unit/lib/index.spec.js
This makes the error rendering middleware also take responsibility for outputting an error page in production environments. In production no error details are leaked and we only render the status code and message, this replicates the behaviour [currently in n-express](https://github.com/Financial-Times/n-express/blob/main/src/lib/instrument-listen.js#L51-L84).
We're doing this to reduce the footprint of n-express (#310) which currently contains some error rendering logic. Once use of the Reliability Kit error rendering middleware is more ubiquitous we should be able to remove the error handling code from n-express in a new major version.
While this is technically a breaking change, if an app is using n-express then it's safe to upgrade. This is because this package behaves in exactly the …
=> feat!: render stripped back errors in production

packages/middleware-render-error-info/README.md, packages/middleware-render-error-info/lib/index.js, packages/middleware-render-error-info/test/unit/lib/index.spec.js
This sets a new header in the error rendering middleware which exposes the fingerprint of an error if it has one. This allows us to better debug in production environments - our logs also include this fingerprint so that you can map our generic error pages to the type of error that occurred and where in the code it was thrown.
* Complete: the `serializeError` method, used in our logging _and_ error rendering, [now adds a `fingerprint` property](https://github.com/Financial-Times/dotcom-reliability-kit/pull/787) to an error object. This fingerprint is a hash of the first two lines of the error stack trace, meaning that the fingerprint can locate an error in our codebase without giving away error information to end-users or attackers
* Complete: the latest version Reliability Kit error …
=> feat: expose error fingerprints as an HTTP header

packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js
We encountered an issue in pino-pretty where, if the `--require` argument is used, the required file will be loaded twice. This can cause some weird and unexpected issues. We raised a bug with pino-pretty here: https://github.com/pinojs/pino-pretty/issues/478
Switching to using pino-pretty as a stream resolves this issue.
=> fix: switch to using streams for prettification

packages/logger/README.md, packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js
Simeon reported in the cp-reliability Slack channel that they would prefer to have more human readable timestamps in logs. Pino supports this with the stdTimeFunctions object which can be set on the withTimestamps option (that we're using already).
This commit exposes the Pino configuration with a new Reliability Kit logger option called useIsoTimeFormat.
We anticipate that in the future we will probably switch this to be the default (which will be a breaking change) and potentially remove the option completely so that timestamps are always logged.
Note that this timestamp option is on the log body. We do already have the log ingestion datetime recorded, even when withTimestamps is false.
=> feat: add useIsoTimeFormat option to format log timestamps

packages/middleware-render-error-info/lib/index.js, packages/middleware-render-error-info/lib/render-error-page.js, packages/middleware-render-error-info/test/unit/lib/__snapshots__/index.spec.js.snap, packages/middleware-render-error-info/test/unit/lib/index.spec.js
This renders the error fingerprint on both the local development and production error pages so that apps that aren't behind FT.com will also get a fingerprint output without having to handle it themselves.
=> feat: render the error fingerprint

docs/contributing.md, docs/getting-started/handling-errors.md, docs/getting-started/logging-errors.md, docs/getting-started/throwing-errors.md, packages/crash-handler/README.md, packages/fetch-error-handler/README.md, packages/log-error/README.md, packages/logger/README.md, packages/middleware-log-errors/README.md, packages/middleware-render-error-info/README.md, packages/serialize-error/README.md
This fixes and revises the [Markdown note/warning blocks](https://github.com/orgs/community/discussions/16925), which GitHub changed the display of a while ago.
=> docs: fix note blocks

.release-please-manifest.json, packages/crash-handler/CHANGELOG.md, packages/crash-handler/package.json, packages/fetch-error-handler/CHANGELOG.md, packages/fetch-error-handler/package.json, packages/log-error/CHANGELOG.md, packages/log-error/package.json, packages/logger/CHANGELOG.md, packages/logger/package.json, packages/middleware-log-errors/CHANGELOG.md, packages/middleware-log-errors/package.json, packages/middleware-render-error-info/CHANGELOG.md, packages/middleware-render-error-info/package.json, packages/serialize-error/CHANGELOG.md, packages/serialize-error/package.json
:rock: I've created a release for you
---
<details><summary>crash-handler: 3.0.9</summary>
* fix the markdown note/warning blocks ([c7f69f2](https://github.com/Financial-Times/dotcom-reliability-kit/commit/c7f69f20a8b000f4a40c4cd25be23fcee2ecd85d))
* revise the note/warning levels ([917abc6](https://github.com/Financial-Times/dotcom-reliability-kit/commit/917abc60a0891f3a9110bafca96fe924a5b76a80))
* The following workspace dependencies were updated
* dependencies
* @dotcom-reliability-kit/log-error bumped from ^3.1.6 to ^3.1.7
</details>
<details><summary>fetch-error-handler: 0.1.2</summary>
* fix the markdown note/warning blocks ([c7f69f2](https://github.com/Financial-Times/dotcom-reliability-kit/commit/c7f69f20a8b000f4a40c4cd25be23fcee2ecd85d))
* revise the note/warning levels …
=> chore: release main

.circleci/config.yml, package-lock.json, package.json, packages/app-info/package.json, packages/crash-handler/package.json, packages/errors/package.json, packages/eslint-config/package.json, packages/fetch-error-handler/package.json, packages/log-error/package.json, packages/logger/package.json, packages/middleware-log-errors/package.json, packages/middleware-render-error-info/package.json, packages/serialize-error/package.json, packages/serialize-request/package.json, resources/logos/package.json
This can't be merged until January 2024 when we're dropping Node.js 16 support from packages. Just getting it ready to save us a job in the new year.
This resolves #806.
=> chore!: drop support for Node.js 16 and npm 7

packages/app-info/README.md, packages/app-info/docs/migration.md, packages/crash-handler/README.md, packages/crash-handler/docs/migration.md, packages/errors/README.md, packages/errors/docs/migration.md, packages/eslint-config/README.md, packages/eslint-config/docs/migration.md, packages/log-error/README.md, packages/log-error/docs/migration.md, packages/logger/README.md, packages/logger/docs/migration.md, packages/middleware-log-errors/README.md, packages/middleware-log-errors/docs/migration.md, packages/middleware-render-error-info/README.md, packages/middleware-render-error-info/docs/migration.md, packages/serialize-error/README.md, packages/serialize-error/docs/migration.md, packages/serialize-request/README.md, packages/serialize-request/docs/migration.md
There's a small maintenance overhead to adding these but I think they're far more clear than a changelog for major breaking versions. We need to include a lot of extra context and information and I think these guides will reduce questions from other teams.
=> docs: add migration guides for all packages

package-lock.json, packages/logger/package.json
These are a hangover from the early logger experiments.
=> chore: remove unused development dependencies

packages/log-error/README.md, packages/logger/test/end-to-end/compatibility-test-cases.js, packages/middleware-log-errors/README.md
To avoid confusion, removed references to Node 16 in docs, now that node16 support bas been dropped by Dotcom-Reliability-kit-> #840
=> docs: replace node 16 references with node 18

packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js
Back in #802 we fixed an issue where we were doubling up logs due to pino-pretty being installed. We switched to streaming logs into pino-pretty instead of configuring it as a transport.
This turned out to be a configuration issue ([see issue comment on Pino](https://github.com/pinojs/pino/issues/1852#issuecomment-1883376351)) which allows us to switch back to configuring pino-pretty as a transport rather than creating a stream. I prefer this approach as it's easier to test and I think results in more readable code.
This is largely a revert of 7abae5a92a012b835a009e4df983bc401223e134, but some related code has changed since this commit so I had to manually switch back to the old way of doing things.
=> fix: switch back to using a pino-pretty transport

packages/opentelemetry/lib/index.js, packages/opentelemetry/test/unit/lib/index.spec.js
This helps identify our OpenTelemetry client and the system that's making the requests, useful for debugging.
=> feat: send a custom user-agent with otel requests

packages/opentelemetry/README.md, packages/opentelemetry/lib/index.js, packages/opentelemetry/setup.js, packages/opentelemetry/test/unit/lib/index.spec.js, packages/opentelemetry/test/unit/setup.spec.js
This tidies up tracing config and paves the way to us having more configurations that are specific to tracing. It will make it easier to add metrics later as well.
This is a breaking change because:
1. Environment variable names have changed
2. The JavaScript API has changed
See-also: https://financialtimes.atlassian.net/browse/CPREL-951
=> feat!: move tracing config into a separate object

packages/opentelemetry/README.md, packages/opentelemetry/lib/index.js, packages/opentelemetry/setup.js, packages/opentelemetry/test/unit/lib/index.spec.js, packages/opentelemetry/test/unit/setup.spec.js
This is a breaking change because an app that updates will no longer see 100% of their traces in their backend.
I decided that working in percentages was better than working in ratios because I think there's less change for confusion.
=> feat!: add the ability to sample traces

packages/opentelemetry/lib/index.js, packages/opentelemetry/test/unit/lib/index.spec.js
This ensures that we can see that OpenTelemetry is running in more apps.
=> feat: log OpenTelemetry success as info

packages/opentelemetry/README.md
This outlines how to use OpenTelemetry in production and local development, and what config changes you might need. I think this is worth documenting as I'm sure we'll get questions relating to this.
I'm deliberately not outlining how we do this in production in Customer Products:
1. This can be used by other teams
2. This will change once we have a central store
3. It's a public repo, we don't want to share our tracing setup here
=> docs: add running instructions

packages/opentelemetry/README.md, packages/opentelemetry/lib/index.js, packages/opentelemetry/test/unit/lib/index.spec.js
This excludes commonly polled URLs from the tracing. By doing this at the instrumentation level we shouldn't impact the percentage of traces that are sampled and we'll see a lot less noise.
=> feat: ignore commonly polled URLs

packages/opentelemetry/README.md
We've tested out this beta package in next-preflight, dotcom-debug-user, and also reliability-dashboards, and feel happy to mark it as stable for other systems to install now in production. This completes CPREL-956
Release-as: 1.0.0
=> docs!: mark as stable

.github/dependabot.yml
We should group OpenTelemetry updates because they're likely to be more frequent than our other dependency bumps. E.g. right now there are 5 different PRs relating to it that we'll otherwise need to merge separately.
=> chore: group OpenTelemetry updates

package-lock.json, packages/opentelemetry/README.md, packages/opentelemetry/package.json
I need to do this manually for now until we merge #912. There's a breaking change in 0.48 but it's only re-removing experimental support for ESM modules, not something we use. However I thought it'd be worth adding a note to the README about this gotcha.
=> fix: update all OpenTelemetry packages

package-lock.json, packages/opentelemetry/lib/index.js, packages/opentelemetry/package.json, packages/opentelemetry/test/unit/lib/index.spec.js
Request URLs can still be invalid and make it all the way into our filter. One way you can cause this error to occur is by not setting a `host` header. We don't want errors to be logged for this so I'm now logging a warning with details about the URL that failed to be parsed.
=> fix: handle invalid URLs in the request filter

.gitignore, jsconfig.build.json, packages/serialize-request/.npmignore, packages/serialize-request/lib/index.js, packages/serialize-request/package.json, packages/serialize-request/types/index.d.ts, scripts/clean-generated-types.sh, test/modules/js-esm-sucrase/index.js, test/modules/js-esm-uncompiled/index.js, test/modules/ts-esm-interop/index.ts, test/modules/ts-esm-nointerop/index.ts
This adds manual type declarations for serialize-request which should make it work in most projects. The tests are now passing.
The compromise is this:
* ✅ In a CommonJS app (non-compiled)
* ✅ In an [ESM](https://nodejs.org/api/esm.html) app (non-compiled)
* ✅ In a TypeScript app that outputs ESM ([`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop) set to `true`)
* ✅ In a TypeScript app that outputs ESM ([`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop) set to `false`)
* ✅ In a CommonJS app which uses [Sucrase](https://sucrase.io/)
* ❌ In a TypeScript app that outputs CommonJS ([`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop) set to `true`)
* ❌ In a TypeScript app that outputs CommonJS …
=> fix: add type declarations for serialize-request

.gitignore, jsconfig.build.json, packages/serialize-error/.npmignore, packages/serialize-error/lib/index.js, packages/serialize-error/package.json, packages/serialize-error/types/index.d.ts, scripts/clean-generated-types.sh
This adds manual type declarations for serialize-error which should make it work in most projects.
See-also: [CPREL-985](https://financialtimes.atlassian.net/browse/CPREL-985)
[CPREL-985]: https://financialtimes.atlassian.net/browse/CPREL-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add type declarations for serialize-error

packages/app-info/.npmignore
Now that we're using manual type declarations in app-info we don't need to unignore the files - they're no longer ignored in the root-level gitignore file.
=> chore: remove unnecessary npmignore entries

package-lock.json, packages/opentelemetry/lib/index.js, packages/opentelemetry/package.json, packages/opentelemetry/test/unit/lib/index.spec.js
None of the individual dependency PRs pass the tests because they're not compatible with the other versions. This bumps everything at once.
There was also a deprecation in semantic resource attributes which was causing some type errors. I've fixed these.
=> fix: bump all OpenTelemetry packages

packages/crash-handler/CHANGELOG.md, packages/log-error/CHANGELOG.md, packages/logger/CHANGELOG.md, packages/middleware-log-errors/CHANGELOG.md, packages/middleware-render-error-info/CHANGELOG.md
I've been wanting to do this for ages and Release Please have finally fixed the issue their end. When dependencies were updated _within_ the monorepo the changelogs didn't get updated correctly with a version heading. I've regenerated all the impacted changelog files based on the GitHub release data.
The bulk of the work was done with a quick script I wrote after pulling the release JSON. I double checked myself and think everything is correct 👍
=> Fix the changelogs

packages/fetch-error-handler/README.md, packages/fetch-error-handler/lib/create-handler.js, packages/fetch-error-handler/test/unit/lib/create-handler.spec.js
node-fetch has a memory leak if you don't read the body of a response. Within the library we don't ever know which fetch implementaton we're using so we've had to test for a property (`pipe`) that only exists on the node-fetch response body and not native fetch.
If we're throwing an error and we see that the response body has this method, then we pipe the body into a black hole stream. This means that the body is unusable if there was an error but we can document this limitation. I'd rather not mess with trying to read/parse data from the response body if possible as it adds a lot of complexity and I don't want to add _too_ many cases to deal with node-fetch when we'll be moving to native-fetch relatively soon.
We discussed some alternatives but I decided the best thing to do for now is …
=> fix: handle node-fetch memory leak

packages/app-info/README.md, packages/app-info/lib/index.js, packages/app-info/test/unit/lib/index.spec.js, packages/app-info/types/index.d.ts
These are all required to add OpenTelemetry metrics, we need to solidify the app info properties that we rely on otherwise our metrics are rejected. This does the following:
* Firms up the `releaseVersion` property, required in our metrics
* Adds in an `instanceId` property, required in our metrics
* Adds aliases for OpenTelemetry semantic conventions, which is the first step towards adopting them fully. We'll deprecate old property names in future (resolves #818)
=> Broad app info improvements (required for OpenTelemetry metrics)

package-lock.json, packages/opentelemetry/README.md, packages/opentelemetry/lib/config/instrumentations.js, packages/opentelemetry/lib/config/resource.js, packages/opentelemetry/lib/config/tracing.js, packages/opentelemetry/lib/config/user-agents.js, packages/opentelemetry/lib/index.js, packages/opentelemetry/package.json, packages/opentelemetry/setup.js, packages/opentelemetry/test/unit/lib/config/instrumentation.spec.js, packages/opentelemetry/test/unit/lib/config/resource.spec.js, packages/opentelemetry/test/unit/lib/config/tracing.spec.js, packages/opentelemetry/test/unit/lib/config/user-agents.spec.js, packages/opentelemetry/test/unit/lib/index.spec.js, packages/opentelemetry/test/unit/setup.spec.js
This refactors the package, splitting things into more testable modules ahead of adding in metrics support. I tried adding support already but the tests get unwieldy and it was difficult to reason about anything; I took a step back and did some refactoring which will make adding metrics a lot easier.
I tested this manually as well by linking it into a local project and testing that traces come through in Jaeger.
=> Refactor the OpenTelemetry package

package-lock.json, packages/app-info/README.md, packages/app-info/lib/index.js, packages/app-info/test/unit/lib/index.spec.js, packages/app-info/types/index.d.ts, packages/opentelemetry/README.md, packages/opentelemetry/docs/migration.md, packages/opentelemetry/lib/config/instrumentations.js, packages/opentelemetry/lib/config/metrics.js, packages/opentelemetry/lib/config/resource.js, packages/opentelemetry/lib/config/tracing.js, packages/opentelemetry/lib/config/user-agents.js, packages/opentelemetry/lib/index.js, packages/opentelemetry/package.json, packages/opentelemetry/setup.js, packages/opentelemetry/test/unit/lib/config/instrumentations.spec.js, packages/opentelemetry/test/unit/lib/config/metrics.spec.js, packages/opentelemetry/test/unit/lib/config/resource.spec.js, packages/opentelemetry/test/unit/lib/config/tracing.spec.js, packages/opentelemetry/test/unit/lib/config/user-agents.spec.js, packages/opentelemetry/test/unit/lib/index.spec.js, packages/opentelemetry/test/unit/setup.spec.js
This adds metrics to the OpenTelemetry package, allowing apps using Reliability Kit to send metrics via the FT's metrics collector. Under the hood this essentially runs the same code as is outlined [in the Tech Hub guide](https://tech.in.ft.com/tech-topics/observability/opentelemetry/heroku) but will less boilerplate required for an app.
Instead of copy/pasting example code, you should now be able to do the following:
Install the Reliability Kit `opentelemetry` package:
```
npm install @dotcom-reliability-kit/opentelemetry
```
Add it to your startup script:
```
node --require @dotcom-reliability-kit/opentelemetry/setup ./my-app.js
```
Add some environment variables to your app (see the [internal collector repo](https://github.com/Financial-Times/observability/tree/main/services/otel-gatewa …
=> Add OpenTelemetry metrics

packages/logger/test/end-to-end/compatibility-test-cases.js
This test illustrates that #1069 is only present when using pino-pretty. In production with JSON logs, the `timestamp` property is present as expected.
=> chore: add a test for 1069

packages/app-info/README.md, packages/app-info/lib/index.js, packages/app-info/test/unit/lib/index.spec.js
We're now looking at more different environment variables to determine the deployment environment the app is running in. `NODE_ENV` by itself isn't sufficient because it's nearly always set to `production` when running on a server, even for staging apps.
This resolves #1111.
=> feat: allow setting the deployment environment

.github/workflows/commitlint.yml
This fails the build when the commit is just a bit long, it's annoying. There's no need - we merge these PRs anyway.
=> chore: don't run commitlint on dependabot PRs

.github/dependabot.yml
Dependabot introduced a `directories` key a while ago which means you can use a single config for all packages in a monorepo instead of having to repeat the config many times.
=> chore: simplify the dependabot config

docs/getting-started/logging-errors.md, packages/log-error/README.md, packages/log-error/lib/index.js, packages/log-error/test/unit/lib/index.spec.js, packages/log-error/types/index.d.ts, packages/middleware-log-errors/README.md, packages/middleware-log-errors/lib/index.js, packages/middleware-log-errors/test/unit/lib/index.spec.js, packages/middleware-log-errors/types/index.d.ts
This adds a `logUserErrorsAsWarnings` option which allows you to change the log level for handled errors. If this option is set to `true` then:
* Errors with a `status` or `statusCode` property of `400`-`499` will be logged with a level of "warn"
* All other errors will still be logged with a level of "error"
I think in future we'll switch this to be the default behaviour and remove the option.
=> feat: add a `logUserErrorsAsWarnings` option

packages/opentelemetry/lib/config/instrumentations.js, packages/opentelemetry/lib/index.js, packages/opentelemetry/test/unit/lib/config/instrumentations.spec.js, packages/opentelemetry/test/unit/lib/index.spec.js
This reduces warnings from the OpenTelemetry package:
- **Disable the pino instrumentation:**
The pino instrumentation is causing us issues because we import our logger before the instrumentation can happen. It's logging an obnoxious warning. I think this is fine to disable because:
1. We use pino to log to stdout so we're not missing a lot of useful info about the way it runs
2. The instrumentation only adds traces, not metrics. We run pino async so it doesn't block further execution and shouldn't impact the timings of the routes etc that use it
3. By default, this instrumentation tries to use the OpenTelemetry logs SDK. I'd rather not load some stuff that we don't want to use.
- **Wrap the Reliability Kit logger:**
We have been losing information from the OpenTelemetry internal logs …
=> Reduce OpenTelemetry warnings

package-lock.json, packages/middleware-log-errors/package.json, packages/middleware-log-errors/test/end-to-end/index.spec.js
I'm not sure why we ever included this, we can just use the native fetch method. It's fine as it's a test. This will reduce the number of annoying dependency bump PRs we get.
=> chore: remove node-fetch

packages/opentelemetry/README.md, packages/opentelemetry/lib/index.js, packages/opentelemetry/setup.js, packages/opentelemetry/test/unit/lib/index.spec.js, packages/opentelemetry/test/unit/setup.spec.js, packages/opentelemetry/types/index.d.ts
These logs are very noisy and provide little to no value. I've disabled them by default but you can enable them via an option or new environment variable in case you're having issues and need to debug.
=> fix: disable OTEL_INTERNALS logs by default

packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js, packages/logger/types/logger.d.ts
Previously we were logging that the level was deprecated if we didn't recognise it. This made it difficult for Content Discovery to debug a logging issue. Now the same issue will log a more specific warning alongside an error so you can trace it back to the place in the source code where the level is being used.
See Slack message from @fenglish [here](https://financialtimes.slack.com/archives/C02B89GEQHF/p1726132897240619).
=> fix: log a better warning if log level is invalid

packages/opentelemetry/lib/index.js
Due to an issue with the Node.js http auto-instrumentations, requests made with node-fetch do not send metrics. See the code comment for the relevant issue.
Requiring `https` here fixes the issue. I think it's best if we solve this in our client rather than require our teams to update their apps. Technically removing this hack will be a breaking change - I think that's fine, we can coordinate with the removal of node-fetch from our libraries and the migration to native fetch.
---
See-also: [CPREL-1169](https://financialtimes.atlassian.net/browse/CPREL-1169)
[CPREL-1169]: https://financialtimes.atlassian.net/browse/CPREL-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: instrument node-fetch properly

README.md, packages/fetch-error-handler/README.md
This library has been used in production for months and is now serving as a replacement for the deprecated `n-fetch` and `n-eager-fetch` libraries.
There have been no reported issues, it's installed in 9 production systems (including content pipeline), and we're seeing ~2m errors per week in Splunk that were successfully handled by this library:
```
index IN (heroku, aws_cloudwatch)
(error.code=FETCH_* OR error.cause.code=FETCH_*)
```
=> Mark fetch-error-handler as stable

.release-please-manifest.json, README.md, package-lock.json, packages/middleware-allow-request-methods/.npmignore, packages/middleware-allow-request-methods/README.md, packages/middleware-allow-request-methods/lib/index.js, packages/middleware-allow-request-methods/package.json, packages/middleware-allow-request-methods/test/unit/lib/index.spec.js, packages/middleware-allow-request-methods/types/index.d.ts, release-please-config.json
Current behaviour: a DDoS can use an unexpected HTTP method to bypass the Fastly cache and cause interruption to service. For example, making a request to the homepage as a POST rather than a GET. Express will return a 404 for this error.
Ideal future work: If we can transform this 404 error into a 405 Method Not Allowed, we may be able to use Signal Sciences to block this kind of attack very quickly. This is because it’s highly unlikely that a genuine user will accidentally make a POST request.
Definition of done for this ticket: Build and release a package containing an Express middleware that applications can consume which will cause unexpected request methods to error with a 405 rather than a 404.
Inspo: https://github.com/rowanmanning/allow-methods/blob/main/index.js
To-Do:
See Also: …
=> feat: manage bad requests with 'allow request methods' package

packages/logger/README.md
This moved from `logging` to `observability` so the link was a 404.
=> docs: fix a broken link

packages/app-info/lib/index.js, packages/app-info/test/unit/lib/index.spec.js
This updates our cloud provider detection to assume AWS if the `HAKO_SERVICE_URL` environment variable is set. At present, the cloud provider will be `null` for Hako apps.
=> feat: set cloud provider to AWS for Hako apps

packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js
pino-pretty doesn't seem to work at all when sending logs to AWS CloudWatch. We also never want prettified logs to be in production, so this protects us against the case where `NODE_ENV` isn't set in an AWS context.
=> fix: disable log prettification on AWS

packages/opentelemetry/lib/config/resource.js, packages/opentelemetry/test/unit/lib/config/resource.spec.js
We missed this breaking change in the migration to v2 of the SDK (#1364). Default resource attributes are no longer merged in automatically when specifying a resource.
=> fix: merge resource attributes with the defaults

package-lock.json, packages/opentelemetry/package.json, packages/opentelemetry/test/end-to-end/fixtures/app.js, packages/opentelemetry/test/end-to-end/fixtures/collector.js, packages/opentelemetry/test/end-to-end/index.spec.js
I wasn't super confident after the recent major update and it led to me doing lots of tests across apps, symlinking in the new package version, and manually checking that metrics and traces were still being sent.
I realised that this could be automated. I've added an end-to-end test where we spin up two Node.js apps - one collector and one regular app with OpenTelemetry added. We capture logs from both and this allows us to verify the basic case of "do metrics/traces get from an app to the configured collector?"
OpenTelemetry uses Protobuf to communicate and it's a real pain to get the parser working. I spent an hour then decided to give up - the key thing is that we see the application's system code in the body that's sent to the collector, we don't want to end up testing OpenTelemetry …
=> test: add end-to-end tests for opentelemetry

packages/logger/README.md
This is just a simple improvement in the docs so the example we use to mock logger also covers cases where the developer invoked Logger constructor in their code.
Feel free to reject if you don't think that's useful or change in case you think there is a better way of doing it.
=> docs: improve mock logger sample

.github/dependabot.yml, docs/contributing.md
Turns out we only need to specify the root directory for Dependabot, @ivomurrell checked this with Tool Kit and Dependabot will update all workspaces.
=> chore: run dependabot against the root directory

.release-please-manifest.json, package-lock.json, packages/client-metrics-web/.npmignore, packages/client-metrics-web/README.md, packages/client-metrics-web/lib/index.js, packages/client-metrics-web/package.json, packages/client-metrics-web/test/unit/lib/index.spec.js, packages/client-metrics-web/types/index.d.ts, release-please-config.json
This adds a lightweight wrapper around the AWS CloudWatch RUM client, ensuring that we're consistent and can send metrics from other libraries that we maintain.
This has been through a long design process, [mostly outlined here](https://financialtimes.atlassian.net/wiki/spaces/DS/pages/8749940842/Design+Document+client-side+observability+improvements). We're also releasing as a `v0.1.0` to allow us to make breaking changes if necessary while we experiment.
The README is a beast, [easier to view like this](https://github.com/Financial-Times/dotcom-reliability-kit/blob/590a5154791369947b292e848e018680da21ca6c/packages/client-metrics-web/README.md).
See-also: [CPREL-1320](https://financialtimes.atlassian.net/browse/CPREL-1320)
[CPREL-1320]: …
=> feat: add a new client-metrics-web package

package-lock.json, packages/opentelemetry/lib/config/instrumentations.js, packages/opentelemetry/package.json, packages/opentelemetry/test/unit/lib/config/instrumentations.spec.js
@opentelemetry/auto-instrumentations-node now imports and initialises @opentelemetry/instrumentation-runtime-node by default, as of v0.58.0.
Because of this we no longer need to intialise it or install it ourselves, this is not a breaking change for us because the initialisation is just moving.
=> fix: update auto-instrumentations

packages/client-metrics-web/README.md
This wasn't as clear as it could have been and it caused some confusion when implementing in Storytelling.
=> docs: clarify how DOM event details map to metrics

.husky/pre-commit, package-lock.json, package.json
I don't think this is needed any more. Most of our editors auto-format, and the build will fail on GitHub if the formatting is off. This slows down committing and introduces a bunch of dependencies.
Closes #1426
=> build: remove lint-staged

packages/logger/types/index.d.ts, packages/logger/types/transforms/legacy-mask.d.ts
These are all issues that raised their head when a TypeScript project in Specialist uses lib checks. Still investigating fully but these are some quick wins to reduce the number of errors
=> fix: correct some type issues with Logger
