README.md, docs/design.md
@JSRedondo suggested this based on the PR comments in #1. I decided to add as a separate document.
=> Add documentation on the design decisions

README.md, jest.config.json, packages/errors/.npmignore, packages/errors/README.md, packages/errors/lib/index.js, packages/errors/lib/operational-error.js, packages/errors/package.json, packages/errors/test/lib/index.spec.js, packages/errors/test/lib/operational-error.spec.js
This is a starting point for some central errors. Most of the code in
here is really to act as an example and it will probably change a lot in
future. This PR is mostly here for us to test that the release process
is working as expected.
This will allow me to delete the "example" package (in a separate PR).
=> feat: initial bootstrapping of the errors package

release-please-config.json
This ensures that documentation and miscellaneous changes appear under
appropriate headings in the CHANGELOG.
=> chore: configure changelog sections

.eslintrc.json, package-lock.json, package.json, packages/errors/lib/operational-error.js, packages/errors/test/lib/operational-error.spec.js
I don't feel strongly about which rules we have enabled here. From a quick look the recommended ones seem sensible and `check-access` is an obvious one that we should comply with.
`require-description-complete-sentence` seems ok although maybe a bit over-zealous?
=> chore: add JSDoc linting

package-lock.json, package.json
Trying this to see if the latest `release-please` is broken.
=> chore(deps): revert release-please to 13.15.0

package-lock.json, package.json
OK this should do it. I tried running it locally and it agrees with / doesn't change the release PR 👍
=> chore: bump release-please from 13.18.6 to 13.19.3

docs/contributing.md, docs/design.md, docs/getting-started/handling-errors.md, docs/getting-started/throwing-errors.md, packages/errors/README.md
A few typo fixes and suggestions to the documentation having read through it.
=> Apply documentation amends

docs/contributing.md
This took me a long time to work out. Let me know if it's not clear, I'm
happy to discuss what I found in person or a call as it's quite
difficult to get into written words!
=> docs: add notes on PR scope and fixing releases

docs/contributing.md
=> docs: write up how to install dependencies

release-please-config.json
Gotta keep up that branding.
[Relevant docs](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#pull-request-header).
=> chore: add a customised release PR message

packages/logger/README.md
=> Fix typo in readme

packages/logger/test/end-to-end/README.md
=> docs: add details on end-to-end tests

packages/eslint-config/README.md, packages/eslint-config/lib/index.js
This sets require-atomic-updates to a warn level as we were seeing it error as a false positive. 
Linked to [JIRA-629](https://financialtimes.atlassian.net/browse/CPREL-629)
=> set require-atomic-updates to warn level

.github/dependabot.yml, .release-please-manifest.json, README.md, package-lock.json, packages/opentelemetry/.npmignore, packages/opentelemetry/README.md, packages/opentelemetry/lib/index.js, packages/opentelemetry/package.json, packages/opentelemetry/setup.js, packages/opentelemetry/test/unit/lib/index.spec.js, packages/opentelemetry/test/unit/setup.spec.js, release-please-config.json
JIRA[CPREL-930]
This creates a new opentelemetry package, where all tests are passing; and can be --required also if the consuming repo wants to use it in this way
Release-As: 0.1.0
=> feat: created new opentelemetry package with tracing functionality

package-lock.json, packages/opentelemetry/package.json
All of these need to be updated together and the dependabot PRs didn't do it right. I checked the breaking changes and none of them impact us.
=> fix: update all the OpenTelemetry packages

.circleci/config.yml, package-lock.json, package.json, packages/app-info/package.json, packages/crash-handler/package.json, packages/errors/package.json, packages/eslint-config/package.json, packages/fetch-error-handler/package.json, packages/log-error/package.json, packages/logger/package.json, packages/logger/test/end-to-end/helpers/split-and-parse-json-logs.js, packages/middleware-log-errors/package.json, packages/middleware-render-error-info/package.json, packages/opentelemetry/package.json, packages/serialize-error/package.json, packages/serialize-request/package.json, resources/logos/package.json
I feel confident enough in our end-to-end tests to add support immediately. v22 will become an LTS release so it's worth testing against it as soon as possible.
=> feat: add support for Node.js 22

package-lock.json, packages/opentelemetry/package.json
I checked the breaking changes and we're not impacted.
=> fix: update all OpenTelemetry packages

resources/splunk-dashboards/src/heroku.json
This adds a new Debug Radar section to the Heroku app dashboard because I'm starting to see another climb in basic TypeErrors.
=> feat: add low-hanging-fruit

packages/logger/README.md, packages/logger/lib/logger.js, packages/logger/test/unit/lib/logger.spec.js, packages/logger/types/logger.d.ts
This resolves #1248 - see this issue for context.
=> feat: add the ability to set custom serializers

package-lock.json, packages/opentelemetry/package.json
I checked through these and none of the breaking changes should impact us this time.
=> fix: bump OpenTelemetry packages

.circleci/config.yml, package-lock.json, package.json, packages/app-info/package.json, packages/client-metrics-web/package.json, packages/crash-handler/package.json, packages/errors/package.json, packages/eslint-config/package.json, packages/fetch-error-handler/package.json, packages/log-error/package.json, packages/logger/package.json, packages/middleware-allow-request-methods/package.json, packages/middleware-log-errors/package.json, packages/middleware-render-error-info/package.json, packages/opentelemetry/package.json, packages/serialize-error/package.json, packages/serialize-request/package.json, resources/logos/package.json
Time to start running tests I guess.
=> feat: add support for Node.js 24
